spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Mysql@1234
    url: jdbc:mysql://localhost:3306/sbms27
    username: root
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    